### PR TITLE
Added MD to HTML conversion

### PR DESCRIPTION
**Pull request by jameshibbard**
Adds a button in the editor toolbar which converts markdown to HTML, as well as inserting the [author_more] shortcode at the top of the article.

### CODE REVIEW

**Comment by Swader** [comment]
>  as well as inserting the [author_more] shortcode at the top of the article

Does it check if the shortcode already exists? Where does it put it? After the first paragraph / at the very top / ?

**Comment by jameshibbard** [comment]
The assumption is that you're copy/pasting an entire article in md format (and thus overwriting whatever is in the editor pane). It doesn't check for it and will happily insert multiple [author_more] tags. It inserts it at the top of the article after the second paragraph (denoted by two consecutive linebreaks).

While it works well for my workflow, I was a bit unsure if I should leave this in. It wouldn't be a hassle to remove it (in which case we could work out what makes sense in this respect and revisit).

**Comment by Swader** [comment]
Let's remove this for now - I often put [author_more] into the MD itself, and save it as such in Github, so that a direct export can be made later with any MD->HTML exporter without having to think about the shortcode. Since MD doesn't react to [whatever] tags without URL definitions matching it, it works just fine. I'm sure others have different approaches, and different positions in which they like to put the tag.

**Comment by jameshibbard** [comment]
Hmm. I'm afraid it'll wrap [author_more] in `<p>` tags. Let me check that and update things. Are you in the habit of committing other WP shortcodes ([whatever] tags) to your repo?

**Comment by Swader** [comment]
Only the author_more one. It does wrap it in `<p>` but that doesn't seem to affect things in my experience.

**Comment by jameshibbard** [comment]
So, if I just change my PR so it doesn't insert [author_more] we're good? Or would you rather I changed `<p>[author_more]</p>` to `[author_more]`? Both is fine.

**Comment by Swader** [comment]
Just remove author_more altogether and let the respective editor handle that. Maybe we can consider a setting in the future where the user can select "auto-insert author_more" or whatnot.

**Comment by jameshibbard** [comment]
Done.

**Pull request merged**
